name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install root dependencies
        run: npm ci

      - name: Start server in the background
        run: npm start &        
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v6
        # with:
        #   wait-on: 'http://[::1]:3000'
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      # - uses: actions/upload-artifact@v3
      #   if: failure()
      #   with:
      #     name: cypress-screenshots
      #     path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: cypress-videos
      #     path: cypress/videos
